services:
    servers:
      image: atlaspharmacy
      container_name: atlaspharmacy
      restart: on-failure
      networks:
        - demo
      ports:
        - 8088:8088
      environment:
        JDBC_DATABASE_PASSWORD: atlaspharmacy
        JDBC_DATABASE_USERNAME: atlaspharmacy
        JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/atlaspharmacy
        
      depends_on: 
        - postgres
  
        
    postgres:
      image: postgres:13
      restart: always
      networks:
       - demo
      environment:
        POSTGRES_PASSWORD: atlaspharmacy
        POSTGRES_USER: atlaspharmacy
        POSTGRES_DB: atlaspharmacy
      volumes:
       - postgres:/var/lib/postgresql/data
      
  
volumes:
    postgres:
        # mysql-data:
  
networks:
    demo:
      name: demo
      driver: bridge